In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("Folds5x2_pp.csv", sep = ',').to_numpy()
cols = ['Temperature', 'AmbientPressure','RelativeHumidity', 'ExhaustVacuum', 'ElectricalEnergy']
df = pd.DataFrame(data , columns = cols)
df

,Temperature,AmbientPressure,RelativeHumidity,ExhaustVacuum,ElectricalEnergy
0,8.34,40.77,1010.84,90.01,480.48
1,23.64,58.49,1011.40,74.20,445.75
2,29.74,56.90,1007.15,41.91,438.76
3,19.07,49.69,1007.22,76.79,453.09
4,11.80,40.66,1017.13,97.20,464.43
...,...,...,...,...,...
9563,15.12,48.92,1011.80,72.93,462.59
9564,33.41,77.95,1010.30,59.72,432.90
9565,15.99,43.34,1014.20,78.66,465.96
9566,17.65,59.87,1018.58,94.65,450.93
9567,23.68,51.30,1011.86,71.24,451.67

In [3]:
X = df.drop(columns = 'ElectricalEnergy').to_numpy()
y = df['ElectricalEnergy'].to_numpy()

(TrainX, testX, Trainy, testy) = train_test_split(X, y, test_size = .25, random_state = 1)

model = LinearRegression(fit_intercept = False)
model.fit(TrainX, Trainy)

predictions = model.predict(testX)

parameters = model.coef_

print('The r^2 score is', r2_score(testy, predictions))
print('The mean absolute error is', mean_absolute_error(testy, predictions))

The r^2 score is 0.9137472320101377
The mean absolute error is 4.0612397684489006

In [4]:
def univariatePolynomialBasis(M):
    def polynomialM(x):
        
        out = np.array([])
        
        for i in range(M+1):
            out = np.append(out, x ** i)
              
        return out
    return polynomialM

In [13]:

poly = univariatePolynomialBasis(2)

Xh = np.apply_along_axis(poly,1,X)

(TrainXh, testXh, Trainy, testy) = train_test_split(Xh, y, test_size = .25, random_state = 1)

model = LinearRegression(fit_intercept = False)
model.fit(TrainXh, Trainy)

predictions = model.predict(testXh)

parameters = model.coef_


print('The r^2 score is', r2_score(testy, predictions))
print('The mean absolute error is', mean_absolute_error(testy, predictions))

The r^2 score is 0.9391932405011701
The mean absolute error is 3.413508154150271